sudo:required
services:
  - docker
# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.2"
before_install:
  - docker version
  - docker info
install:
	- npm install newman
	- "pip install -r requirements.txt"
before_script:
	- node --version
	- npm --version
	- node_modules/.bin/newman --version  
    
script:
  - nosetests
  - docker build -t my_docker_reposetory/swagger_server:1.0.0 .
  - docker run --name example_api -d -t -p 127.0.0.1:8080:8080 my/swagger-spring-example:1.0.0
  - docker ps
  - count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break; fi; done
  - docker logs example_api
  - node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
